import _CreateUserForm from './CreateUserForm';
import _EducationInformationForm from './EducationInformationForm';
import _Miscellaneous from './MiscellaneousForm';
import _NationalTestForm from './NationalTestForm';
import _PersonalInformationForm from './PersonalInformationForm';
import _ResetPasswordForm from './ResetPasswordForm';
import _SignInForm from './SignInForm';
import _SignUpForm from './SignUpForm';
import _StartApplicationForm from './StartApplicationForm';
import _USTestForm from './USTestForm';

export const CreateUserForm = _CreateUserForm;
export const EducationInformationForm = _EducationInformationForm;
export const Miscellaneous = _Miscellaneous;
export const NationalTestForm = _NationalTestForm;
export const PersonalInformationForm = _PersonalInformationForm;
export const ResetPasswordForm = _ResetPasswordForm;
export const SignInForm = _SignInForm;
export const SignUpForm = _SignUpForm;
export const StartApplicationForm = _StartApplicationForm;
export const USTestForm = _USTestForm;
