// AHMBURGER MENU Actions
export const OPEN_HAMBURGER = "OPEN_HAMBURGER";
export const CLOSE_HAMBURGER = "CLOSE_HAMBURGER";

// AUTH Actions
export const REMOVE_AUTH_ERRORS = "REMOVE_AUTH_ERRORS";
export const SIGN_IN_AUTHORIZING = "SIGN_IN_AUTHORIZING";
export const SIGN_IN_GETTING_USER = "SIGN_IN_GETTING_USER";
export const SIGNED_IN = "SIGNED_IN";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT_AUTHORIZING = "SIGN_OUT_AUTHORIZING";
export const SIGNED_OUT = "SIGNED_OUT";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";
export const ACCOUNT_CREATION_INITIATED = "ACCOUNT_CREATION_INITIATED";
export const ACCOUNT_CREATION_FAILED = "ACCOUNT_CREATION_FAILED";
export const ACCOUNT_CREATED = "ACCOUNT_CREATED";
export const ACCOUNT_CREATION_ADDING_TO_USER_DBS ="ACCOUNT_CREATION_ADDING_TO_USER_DBS";
export const ACCOUNT_CREATION_ADDING_TO_USER_DBS_FAILED = "ACCOUNT_CREATION_ADDING_TO_USER_DBS_FAILED";
export const RESET_PASSWORD_EMAIL_INITIATED = "RESET_PASSWORD_EMAIL_INITIATED";
export const RESET_PASSWORD_EMAIL_SENT = "RESET_PASSWORD_EMAIL_SENT";
export const RESET_PASSWORD_EMAIL_FAILED = "RESET_PASSWORD_EMAIL_FAILED";
export const EMAIL_CONFIRMATION_SEND_INITIATED = "EMAIL_CONFIRMATION_SEND_INITIATED";
export const EMAIL_CONFIRMATION_SENT = "EMAIL_CONFIRMATION_SENT";
export const EMAIL_CONFIRMATION_SEND_FAILED = "EMAIL_CONFIRMATION_SEND_FAILED";

// AVATAR Actions
export const AVATAR_GET_INITIATED = "AVATAR_GET_INITIATED";
export const AVATAR_GET_FAILED = "AVATAR_GET_FAILED";
export const AVATAR_GET_DONE = "AVATAR_GET_DONE";
export const AVATAR_UPLOAD_INITIATED = "AVATAR_UPLOAD_INITIATED";
export const AVATAR_UPLOAD_FAILED = "AVATAR_UPLOAD_FAILED";
export const AVATAR_UPLOADED = "AVATAR_UPLOADED";

// USER actions
export const USER_GET_INITIATED = "USER_GET_INITIATED";
export const USER_UPDATE_INITIATED = "USER_UPDATE_INITIATED";
export const USER_GET_FAILED = "USER_GET_FAILED";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_UPDATED = "USER_UPDATED";
export const USER_AUTH_EMAIL_UPDATE_INITIATED = "USER_AUTH_EMAIL_UPDATE_INITIATED";
export const USER_AUTH_EMAIL_UPDATED = "USER_AUTH_EMAIL_UPDATED";
export const USER_AUTH_EMAIL_UPDATE_FAILED = "USER_AUTH_EMAIL_UPDATE_FAILED";
export const USER_REAUTHENTICATION_INITIATED = "USER_REAUTHENTICATION_INITIATED";
export const USER_REAUTHENTICATED = "USER_REAUTHENTICATED";
export const USER_REAUTHENTICATION_FAILED = "USER_REAUTHENTICATION_FAILED";

// APPLICATION actions
export const APPLICATION_GET_INITIATED = "APPLICATION_GET_INITIATED";
export const APPLICATION_UPDATE_INITIATED = "APPLICATION_UPDATE_INITIATED";
export const APPLICATION_GET_FAILED = "APPLICATION_GET_FAILED";
export const APPLICATION_UPDATE_FAILED = "APPLICATION_UPDATE_FAILED";
export const APPLICATION_GET_SUCCESS = "APPLICATION_GET_SUCCESS";
export const APPLICATION_UPDATED = "APPLICATION_UPDATED";
export const APPLICATION_TEST_DELETE_INITIATED = "APPLICATION_TEST_DELETE_INITIATED";
export const APPLICATION_TEST_DELETE_FAILED = "APPLICATION_TEST_DELETE_FAILED";
export const APPLICATION_TEST_DELETED = "APPLICATION_TEST_DELETED";
export const APPLICATION_SUBMIT_INITIATED = "APPLICATION_SUBMIT_INITIATED";
export const APPLICATION_SUBMIT_FAILED = "APPLICATION_SUBMIT_FAILED";
export const APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED";
export const APPLICATION_SUBMITTED_EMAIL_INITIATED = "APPLICATION_SUBMITTED_EMAIL_INITIATED";
export const APPLICATION_SUBMITTED_EMAIL_SENT = "APPLICATION_SUBMITTED_EMAIL_SENT";
export const APPLICATION_SUBMITTED_EMAIL_FAILED = "APPLICATION_SUBMITTED_EMAIL_FAILED";

// APPLICATIONS actions
export const APPLICATIONS_GET_INITIATED = "APPLICATIONS_GET_INITIATED";
export const APPLICATIONS_GET_FAILED = "APPLICATIONS_GET_FAILED";
export const APPLICATIONS_GET_SUCCESS = "APPLICATIONS_GET_SUCCESS";