// AHMBURGER MENU Actions
export const OPEN_HAMBURGER = "OPEN_HAMBURGER";
export const CLOSE_HAMBURGER = "CLOSE_HAMBURGER";

// AUTH Actions
export const SIGN_IN_AUTHORIZING = "SIGN_IN_AUTHORIZING";
export const SIGN_IN_GETTING_USER = "SIGN_IN_GETTING_USER";
export const SIGNED_IN = "SIGNED_IN";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT_AUTHORIZING = "SIGN_OUT_AUTHORIZING";
export const SIGNED_OUT = "SIGNED_OUT";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

// AVATAR Actions
export const AVATAR_GET_INITIATED = "AVATAR_GET_INITIATED";
export const AVATAR_GET_FAILED = "AVATAR_GET_FAILED";
export const AVATAR_GET_DONE = "AVATAR_GET_DONE";
export const AVATAR_UPLOAD_INITIATED = "AVATAR_UPLOAD_INITIATED";
export const AVATAR_UPLOAD_FAILED = "AVATAR_UPLOAD_FAILED";
export const AVATAR_UPLOADED = "AVATAR_UPLOADED";

// USER actions
export const USER_GET_INITIATED = "USER_GET_INITIATED";
export const USER_UPDATE_INITIATED = "USER_UPDATE_INITIATED";
export const USER_GET_FAILED = "USER_GET_FAILED";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_UPDATED = "USER_UPDATED";
