export enum Hamburger {
  Open = 0,
  Close = 1,
}

export enum Menu {
  Full = 0,
  Compact = 1,
  Closed = 2,
}

export enum Auth {
  RemoveErrors = 0,
  SignInAuthorizing = 1,
  SignInAuthorizing_Social = 2,
  SignedIn = 3,
  SignedIn_Social = 4,
  SignInFailed = 5,
  SignInFailed_Social = 6,
  GettingUser = 7,
  CreatingAccount = 8,
  CreatingAccount_Social = 9,
  CreatedAccount = 10,
  CreatedAccount_Social = 11,
  CreatingAccountFailed = 12,
  CreatingAccountFailed_Social = 13,
  AddingToDb = 14,
  AddedToDb = 15,
  AddingToDbFailed = 16,
  SignOutAuthorizing = 17,
  SignedOut = 18,
  SignOutFailed = 19,
  ResetPasswordEmailSending = 20,
  ResetPasswordEmailSent = 21,
  ResetPasswordEmailFailed = 22,
  AccountCreatedEmailSending = 23,
  AccountCreatedEmailSent = 24,
  AccountCreatedEmailFailed = 25,
  LinkingSocialAccount = 26,
  LinkedSocialAccount = 27,
  LinkingSocialAccountFailed = 28,
  UnlinkingSocialAccount = 29,
  UnlinkedSocialAccount = 30,
  UnlinkingSocialAccountFailed = 31,
  AddingPasswordProvider = 32,
  AddedPasswordProvider = 33,
  AddingPasswordProviderFailed = 34,
  ChangingEmailAddress = 35,
  ChangedEmailAddress = 36,
  ChangingEmailAddressFailed = 37,
}

export enum ProfilePicture {
  GettingProfilePicture = 0,
  GettingProfilePictureFailed = 1,
  GotProfilePicture = 2,
  GettingProfilePicture_ByUid = 3,
  GettingProfilePictureFailed_ByUid = 4,
  GotProfilePicture_ByUid = 5,
  UploadingProfilePicture = 6,
  UploadingProfilePictureFailed = 7,
  UploadedProfilePicture = 8,
}

export enum User {
  GettingUser = 0,
  GettingUserFailed = 1,
  GotUser = 2,
  UpdatingUser = 3,
  UpdatingUserFailed = 4,
  UpdatedUser = 5,
  UpdatingUserEmail = 6,
  UpdatingUserEmailFailed = 7,
  UpdatedUserEmail = 8,
  ReauthenticatingUser = 9,
  ReauthentcatingUserFailed = 10,
  ReauthenticatedUser = 11,
}

export enum Users {
  GettingUsers = 0,
  GettingUsersFailed = 1,
  GotUsers = 2,
  GettingUser = 3,
  GettingUserFailed = 4,
  GotUser = 5,
  GettingUsers_ByUid = 6,
  GettingUsersFailed_ByUid = 7,
  GotUsers_ByUid = 8,
  CreatingUser = 9,
  CreatingUserFailed = 10,
  CreatedUser = 11,
  SendingSignUpEmail = 12,
  SendingSignUpEmailFailed = 13,
  SentSignUpEmail = 14,
  UpdatingUser = 15,
  UpdatingUserFailed = 16,
  UpdatedUser = 17,
  AddingBio = 18,
  AddingBioFailed = 19,
  AddedBio = 20,
  GettingFounder = 21,
  GettingFounderFailed = 22,
  GotFounder = 23,
  GettingStaff = 24,
  GettingStaffFailed = 25,
  GotStaff = 26,
}

export enum Application {
  GettingApplication = 0,
  GettingApplicationFailed = 1,
  GotApplication = 2,
  GettingApplications = 3,
  GettingApplicationsFailed = 4,
  GotApplications = 5,
  UpdatingApplication = 6,
  UpdatingApplicationFailed = 7,
  UpdatedApplication = 8,
  DeletingTest = 9,
  DeletingTestFailed = 10,
  DeletedTest = 11,
  SubmittingApplication = 12,
  SubmittingApplicationFailed = 13,
  SubmittedApplication = 14,
  SendingSubmissionEmail = 15,
  SendingSubmissionEmailFailed = 16,
  SentSubmissionEmail = 17,
}

export enum Stats {
  GettingStats = 0,
  GettingStatsFailed = 1,
  GotStats = 2
}

export enum Student {
  GettingStudent = 0,
  GettingStudentFailed = 1,
  GotStudent = 2,
  UpdatingStudent = 3,
  UpdatingStudentFailed = 4,
  UpdatedStudent = 5,
  DeletingStudentAccomplishment = 6,
  DeletingStudentAccomplishmentFailed = 7,
  DeletedStudentAccomplishment = 8,
  CreatingStudent = 9,
  CreatingStudentFailed = 10,
  CreatedStudent = 11,
}

export enum Students {
  GettingStudents = 0,
  GettingStudentsFailed,
  GotStudents,
  GotCurrentStudents,
  GotPastStudents,
}

export enum Features {
  GettingFeatures = 0,
  GettingFeaturesFailed = 1,
  GotFeatures = 2,
  GettingActiveFeatures = 3,
  GettingActiveFeaturesFailed = 4,
  GotActiveFeatures = 5,
}

export enum Feature {
  GettingFeature = 0,
  GettingFeatureFailed = 1,
  GotFeature = 2,
  UpdatingFeature = 3,
  UpdatingFeatureFailed = 4,
  UpdatedFeature = 5,
  CreatingFeature = 6,
  CreatingFeatureFailed = 7,
  CreatedFeature = 8,
  DeletingFeature = 9,
  DeletingFeatureFailed = 10,
  DeletedFeature = 11
}

export enum Post {
  CreatingPost = 0,
  CreatingPostFailed = 1,
  CreatedPost = 2,
  GettingPost = 3,
  GettingPostFailed = 4,
  GotPost = 5,
  UpdatingPost = 6,
  UpdatingPostFailed = 7,
  UpdatedPost = 8,
  UpdatingHero = 9,
  UpdatingHeroFailed = 10,
  UpdatedHero = 11,
  GettingHero = 12,
  GettingHeroFailed = 13,
  GotHero = 14,
  UpdateLocalConversationsCount = 15,
  DeletingPost = 16,
  DeletingPostFailed = 17,
  DeletedPost = 18,
}

export enum Posts {
  GettingPosts = 0,
  GettingPostsFailed = 1,
  GotPosts = 2,
  GettingMostRecentPosts = 3,
  GettingMostRecentPostsFailed = 4,
  GotMostRecentPosts = 5,
  GettingMostRecentPosts_ByCategory = 6,
  GettingMostRecentPostsFailed_ByCategory = 7,
  GotMostRecentPosts_ByCategory = 8,
  PaginatingPosts = 9,
  PaginatingPostFailed = 10,
  PaginatedPosts = 11,
  GettingAccomplishments = 12,
  GettingAccomplishmentsFailed = 13,
  GotAccomplishments = 14,
}

export enum Category {
  GettingCategory = 0,
  GettingCategoryFailed = 1,
  GotCategory = 2,
  AddingCategory = 3,
  AddingCategoryFailed = 4,
  AddedCategory = 5,
  UpdatingCategory = 6,
  UpdatingCategoryFailed = 7,
  UpdatedCategory = 8,
  GettingCategories = 9,
  GettingCategoriesFailed = 10,
  GotCategories = 11,
  UpdatingCategoryPosts = 12,
  UpdatingCategoryPostsFailed = 13,
  UpdatedCategoryPosts = 14,
}

export enum Comment {
  CreatingComment = 0,
  CreatingCommentFailed = 1,
  CreatedComment = 2,
  DeletingComment = 3,
  DeletingCommentFailed = 4,
  DeletedComment = 5,
  SafelyDeletingComment = 6,
  SafelyDeletingCommentFailed = 7,
  SafelyDeletedComment = 8,
  GettingComment = 9,
  GettingCommentFailed = 10,
  GotComment = 11,
  GettingComments = 12,
  GettingCommentsFailed = 13,
  GotComments = 14,
  GettingReply = 15,
  GettingReplyFailed = 16,
  GotReply = 17,
  GettingReplies = 18,
  GettingRepliesFailed = 19,
  GotReplies = 20,
  UpdatingComment = 21,
  UpdatingCommentFailed = 22,
  UpdatedComment = 23,
  UpdateCommentLocal = 24,
  GettingConversations = 25,
  GettingConversationsFailed = 26,
  GotConversations = 27,
}

export enum Event {
  CreatingEvent = 0,
  CreatingEventFailed = 1,
  CreatedEvent = 2
}

export default {
  Application,
  Auth,
  Category,
  Comment,
  Event,
  Feature,
  Features,
  Hamburger,
  Menu,
  Post,
  Posts,
  ProfilePicture,
  Stats,
  Student, 
  Students,
  User,
  Users,
};